### ISSUE TITLE
Sponsor ZAP project

### ISSUE THREAD

**Issue by psiinon** [RedHatProductSecurity/rapidast#1]
Great to see you're using ZAP.
If you'd like to have a chat with the ZAP core team then just get in touch - my username at Gmail.
I'll get you added to https://www.zaproxy.org/third-party-services/
Sponsorship of ZAP is always appreciated - see https://www.zaproxy.org/supporters/ for more details.

**Comment by jeremychoi** [comment]
thanks. since we discussed in the email, i'll close this.
