### ISSUE TITLE
Can't run any local policies with containers/Dockerfile.multiuser

### ISSUE THREAD

**Issue by paigerube14** [RedHatProductSecurity/rapidast#108]
With trying to use an image built with the Dockerfile.multiuser, I get the below error and I noticed the dockerfile does not copy any policy files like the Dockerfile does 

`cp: cannot create regular file '/home/rapidast/.ZAP/policies': No such file or directory`

**Comment by jeremychoi** [comment]
Hi Paige, did you run with Helm? currently the multiuser image is not supposed to be used with Helm.

**Comment by paigerube14** [comment]
@jeremychoi thanks for the information. The multi user dockerfile was what Cedric had pointed me to, so that's what I had tried originally 
Yes when we are going to be running fully using helm

**Comment by jeremychoi** [comment]
closing this, 2.2.1 merged Containerfile.multiuser into a single Containerfile. And the issue has been fixed.
