### ISSUE TITLE
Fail Deploy Rapidast on Openshift

### ISSUE THREAD

**Issue by Crisbravoon** [RedHatProductSecurity/rapidast#140]
Hi, I am trying to run RapiDast in Openshift and I am having some problems. 
I added this environment variable APP_FILE = ./rapidast.py. 
because I got this error: 

```
Error: don't know how to run your application.
Please set either APP_MODULE, APP_FILE or APP_SCRIPT environment variables, or create a file 'app.py' to launch your appliaction.
```

After performing this modification, an error is displayed indicating that the file or directory ./config/config.yaml' is not found.
Next, I attach an image that shows in more detail the current error.
```
---> Running application from Python script (./rapidast.py) ...
Traceback (most recent call last):
File "/opt/app-root/src/./rapidast.py", line 203, in <module>
run()
File "/opt/app-root/src/./rapidast.py", line 159, in run
yaml.safe_load(load_config_file(parser.parse_args().config_file))
File "/opt/app-root/src/./rapidast.py", line 55, in load_config_file
return open(config_file_location, mode="r", encoding="utf-8")
FileNotFoundError: [Errno 2] No such file or directory: './config/config.yaml'
```

**Comment by jeremychoi** [comment]
Hi. You will need to input a config file when running it. e.g.
./rapidast.py --config <config-file>

The config file can be created, by copying one of the templates under the /config dir, and modifying a few options according to your envioronment.

Also if you'd like to run one on OpenShift, you could try out the Helm chart.

**Comment by Crisbravoon** [comment]
Hi I have used a copy of config-template-zap-simple-yaml, configuring the URL and apiUrl, but when lifting the pod in OCP 4.10 , I get the following error:

![image](https://github.com/RedHatProductSecurity/rapidast/assets/72889787/dc4a9add-f268-4655-8f22-113721b7a86c)

I have raised a Ticket at Red Hat , but they tell me as it is third party product they do not have support from their side.

**Comment by jeremychoi** [comment]
For the error issue above, where RapiDAST is going to be run as a container in the cluster with  `general.container.type: "none"` needs to be configured. E.g., at the line https://github.com/RedHatProductSecurity/rapidast/blob/development/config/config-template-zap-simple.yaml#L37, instead of "podman". 

Please feel free to open another issue for any RapiDAST related technical issues.
