### ISSUE TITLE
ascanrulesBeta addon missing from owasp/zap2docker-stable image

### ISSUE THREAD

**Issue by lpardoRH** [RedHatProductSecurity/rapidast#15]
the following error is present on both daemon and UI version
Failed to find Add-on: ascanrulesBeta

Apparently the addon is missing from the MarketPlace
![Screenshot from 2022-04-26 17-41-57](https://user-images.githubusercontent.com/37450412/165391884-239bae31-807f-47d0-92b2-129d76c75780.png)

If so, an issue should be raised in https://groups.google.com/g/zaproxy-develop

**Comment by jeremychoi** [comment]
In my case, updating with 2.11.1 solved the issue. Can you check if it happens with the latest stable version? (2.11.1).
