### ISSUE TITLE
Provided helm chart does not work on OpenShift

### ISSUE THREAD

**Issue by amisevsk** [RedHatProductSecurity/rapidast#153]
On OpenShift, the Job spawned by the helm chart fails to run every time because the `quay.io/redhatproductsecurity/rapidast:latest` image does not grant appropriate permissions for the `/home/rapidast` directory:
```bash
sh-5.1$ id
uid=1000710000(1000710000) gid=0(root) groups=0(root),1000710000

sh-5.1$ ls -l /home/
total 0
drwx------. 1 rapidast rapidast 74 Oct 23 22:36 rapidast

sh-5.1$ ls /home/rapidast
ls: cannot open directory '/home/rapidast': Permission denied
```

On OpenShift, pods are run with semi-random UIDs so special steps generally need to be taken when granting file/directory permissions (see [OpenShift docs](https://docs.openshift.com/container-platform/4.14/openshift_images/create-images.html#use-uid_create-images) for details). 

Since `/home/rapidast` does not have the execute flag set, it cannot be traversed by the (random UID) user in the pod, causing the default [`command`](https://github.com/RedHatProductSecurity/rapidast/blob/development/helm/chart/templates/_helpers.tpl#L49) of
```
- "sh"
- "-c"
- "cp /helm/config/helmcustomscan.policy /home/rapidast/.ZAP/policies/helm-custom-scan.policy && rapidast.py --config /helm/config/rapidastconfig.yaml"
```
to fail with 
```
cp: failed to access '/home/rapidast/.ZAP/policies/helm-custom-scan.policy': Permission denied
```

**Comment by jeremychoi** [comment]
Thanks for raising this. https://github.com/RedHatProductSecurity/rapidast/commit/24f28ae2e409dfc9d40f5bbbf7718aab73d90b69 should fix this. To apply the fix, using a newly built RapiDAST image is needed. In the meantime, please try building your own image and seeing if it works.

**Comment by jeremychoi** [comment]
pls reopen if the same issue happens.
