### ISSUE TITLE
Please update/correct config*.yaml names on Configuration section

### ISSUE THREAD

**Issue by tshefi** [RedHatProductSecurity/rapidast#158]
Minor issue, on configuration [here](https://github.com/RedHatProductSecurity/rapidast#configuration) we reference:

See **config/config-template.yaml**(a simple version) and **config/config-template-long.yaml**(an exhaustive version) for examples. Each can be used.

No such files currently exist under config/
$ ls
config-template-generic-scan.yaml  config-template-zap-mac.yaml
config-template-multi-scan.yaml    config-template-zap-simple.yaml
config-template-zap-long.yaml

Thanks

**Comment by cedricbu** [comment]
Thanks! you are correct.
