### ISSUE TITLE
RapiDAST scanning using "importUrlsFromFile" is not working properly

### ISSUE THREAD

**Issue by Paramvir-JIndal** [RedHatProductSecurity/rapidast#163]
For offerings that provide REST APIs but no OpenAPI definition, it would be helpful if we can scan the URIs importing from file but this doesn't seem to work. File is getting imported but URIs are not scanned :

config : 

    scanners:
      zap:
        importUrlsFromFile: "/home/pjindal/NotBackedUp/RapiDAST-JDG/new/api-url.txt"

        miscOptions:
          overrideConfigs:
            - formhandler.fields.field(0).fieldId=name
            - formhandler.fields.field(0).value=Test-cache
            - formhandler.fields.field(1).fieldId=cacheName
            - formhandler.fields.field(1).value=Test-cache

api-uri.txt : 

/rest/v2/caches/{name}?action=config
/rest/v2/caches/{name}?action=stats
/rest/v2/caches/{name}?action=distribution
/rest/v2/caches/{name}?action=get-mutable-attributes
/rest/v2/caches/mycache?action=get-mutable-attributes&full=true
/rest/v2/caches/{cacheName}?action=keys
/rest/v2/caches/{cacheName}?action=entries
/rest/v2/caches/{cacheName}?action=size
/rest/v2/caches/{cacheName}?action=stats

Scan is completed but no findings as URIs are not scanned.
[session.tar.gz](https://github.com/RedHatProductSecurity/rapidast/files/14135495/session.tar.gz)

**Comment by jeremychoi** [comment]
@Paramvir-JIndal  did you add 'passiveScan' or 'activeScan' in your config file by any chance? Could you post your full config file?

**Comment by Paramvir-JIndal** [comment]
yes both : 


        passiveScan:
          # optional list of passive rules to disable
          disabledRules: "2,10015,10024,10027,10054,10096,10109,10112"
     

        activeScan:
          policy: "API-scan-minimal"


[config.yaml.txt](https://github.com/RedHatProductSecurity/rapidast/files/14160350/config.yaml.txt)

**Comment by cedricbu** [comment]
Reproducing the issue:
It seems that the import file should contain the entire URL: https://example.com./rest/v2/....

**Comment by Paramvir-JIndal** [comment]
@cedricbu Thanks, it worked perfectly after adding the full URLs in the text file.
